// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPZxxTuIoew0rcJVb-h-WM-5BtU4OlcIM',
    appId: '1:198461873701:web:2e93459247192c5195e9cc',
    messagingSenderId: '198461873701',
    projectId: 'trippr-flutter',
    authDomain: 'trippr-flutter.firebaseapp.com',
    storageBucket: 'trippr-flutter.firebasestorage.app',
    measurementId: 'G-XV5KC7SYSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYSnujtC9m8KTQ0rzcVXrrpkTv0DOkh-c',
    appId: '1:198461873701:android:350d8b40cca2640295e9cc',
    messagingSenderId: '198461873701',
    projectId: 'trippr-flutter',
    storageBucket: 'trippr-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlwjIQGI7bmrF08N_BwnTzmxgc4Mcr7xU',
    appId: '1:198461873701:ios:4f13cc327f8c0fd995e9cc',
    messagingSenderId: '198461873701',
    projectId: 'trippr-flutter',
    storageBucket: 'trippr-flutter.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
